### PR TITLE
Release 1.0 Test

### PR DESCRIPTION
**Pull request by DM1122**

### CODE REVIEW

**Comment by DM1122** [comment]
@dosu-bot please review the code in this PR

**Comment by devstein** [comment]
@DM1122 Dosu doesn't support generic code reviews

**Comment by devstein** [comment]
This is quite a diff to review 😂

**Comment by DM1122** [comment]
> @DM1122 Dosu doesn't support generic code reviews

@devstein I remember you mentioned this, I was curious how it would respond 😅

**Pull request closed without merging**
